"""02 - RAG-Fusion without a language model.

RAG-Fusion sends several rewrites of the question to the retriever and fuses the
rankings with RRF. The rewrites are normally produced by an LLM, which makes the
technique expensive, non-deterministic, and hard to attribute: if it wins, was it
the fusion or the model's paraphrase?

This project separates the two. The rewrites here are generated by rules -- no
model, no API, no randomness -- so whatever RRF over multiple queries is worth,
this measures it in isolation. If rule-based fusion captures most of the gain,
the LLM rewriter is an expensive way to buy the last few points.

Five rule-based views of a question, none of which need to understand it:

    original     the question as asked
    keywords     stopwords stripped, content words only
    entities     capitalised spans -- the names a bridge question hinges on
    quoted       quoted phrases and title-case runs kept intact
    split        clauses split on ' and ' / ' or ' / ',' -- one sub-query each

    python run.py
"""

from __future__ import annotations

import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from shared.corpus import load  # noqa: E402
from shared.metrics import evaluate  # noqa: E402
from shared.pipeline import Index  # noqa: E402
from shared.retrieval import rrf, tokenize  # noqa: E402

HERE = Path(__file__).resolve().parent
N_QUESTIONS = 1500
DEPTH = 20
POOL = 50

_ENTITY = re.compile(
    r"\b(?:[A-Z][\w'’-]*)(?:\s+(?:of|the|de|van|da|and)\s+[A-Z][\w'’-]*|\s+[A-Z][\w'’-]*)*"
)
_SPLIT = re.compile(r"\s+and\s+|\s+or\s+|,\s+|\?\s*")


def variant_keywords(q: str) -> str:
    return " ".join(tokenize(q))


def variant_entities(q: str) -> str:
    # Drop the leading capital of the first word: "Were Scott Derrickson..." should
    # not contribute "Were" as an entity.
    body = q[0].lower() + q[1:] if q else q
    found = [m.group(0).strip() for m in _ENTITY.finditer(body)]
    found = [f for f in found if len(f) > 2]
    return " ".join(found) if found else variant_keywords(q)


def variant_quoted(q: str) -> str:
    quoted = re.findall(r'"([^"]+)"|“([^”]+)”', q)
    flat = [a or b for a, b in quoted]
    return " ".join(flat) if flat else variant_entities(q)


def variant_split(q: str) -> list[str]:
    parts = [p.strip() for p in _SPLIT.split(q) if len(p.strip().split()) >= 3]
    return parts if len(parts) > 1 else []


VARIANTS = {
    "keywords": lambda q: [variant_keywords(q)],
    "entities": lambda q: [variant_entities(q)],
    "quoted": lambda q: [variant_quoted(q)],
    "split": variant_split,
}


def fuse(index: Index, queries_text: list[str], k: int) -> list[int]:
    rankings = []
    for qt in queries_text:
        if not qt.strip():
            continue
        rankings.append(index.bm25.search(qt, POOL))
        rankings.append(index.dense.search(qt, POOL))  # type: ignore[union-attr]
    if not rankings:
        return []
    return [d for d, _ in rrf(rankings, k=k)]


def main() -> None:
    corpus, queries = load(N_QUESTIONS)
    print(f"corpus: {len(corpus)} passages, queries: {len(queries)}\n")
    index = Index.build(corpus)

    configs = {
        "baseline (original only)": ["original"],
        "original + keywords": ["original", "keywords"],
        "original + entities": ["original", "entities"],
        "original + split": ["original", "split"],
        "original + keywords + entities": ["original", "keywords", "entities"],
        "all five views": ["original", "keywords", "entities", "quoted", "split"],
    }

    results = {}
    for name, views in configs.items():
        t0 = time.time()
        rankings = []
        n_subqueries = 0
        for q in queries:
            texts = [q.question] if "original" in views else []
            for v in views:
                if v == "original":
                    continue
                texts.extend(VARIANTS[v](q.question))
            texts = [t for t in dict.fromkeys(texts) if t.strip()]
            n_subqueries += len(texts)
            rankings.append((fuse(index, texts, DEPTH), q.gold_doc_ids))
        scores = evaluate(rankings, seconds=time.time() - t0)
        d = scores.as_dict()
        d["mean_subqueries"] = round(n_subqueries / len(queries), 2)
        results[name] = d
        print(
            f"{name:34} mrr={d['mrr']:.3f}  recall@10={d['recall'][10]:.3f}  "
            f"answerable@10={d['answerable'][10]:.3f}  "
            f"queries/question={d['mean_subqueries']:.2f}  ({d['seconds']}s)"
        )

    out = HERE / "results.json"
    out.write_text(
        json.dumps({"n_questions": len(queries), "depth": DEPTH, "results": results}, indent=2),
        encoding="utf-8",
    )
    print(f"\nwritten to {out.name}")


if __name__ == "__main__":
    main()
